nuxeo/nuxeo-ui-elements

- nuxeo-slots.html
Array.prototype.sort method should return a positive or negative number : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
With your implementation it doesn't work on IE for instance.
> Fix sort array

- nuxeo-error.html
- nuxeo-layout.html
- nuxeo-ui-elements.html
- test/nuxeo-layout.html
Introduces `nuxeo-layout` and brings in `nuxeo-error` for convenience.
> ELEMENTS-220: introduce nuxeo-layout

- nuxeo-page-provider-display-behavior.html
…conditional assingment to this.size to avoid 'not defined' exceptiont
> ELEMENTS-224  - Adds observer to items.splices instead of items

- demo/widgets/index.html
- nuxeo-format-behavior.html
- widgets/nuxeo-date.html
> ELEMENTS-274 : Introduce nuxeo-date element

- better-dateinput-polyfill.html
- bower.json
- nuxeo-document-permissions/nuxeo-document-permissions.html
- widgets/nuxeo-date-picker.html
> ELEMENTS-335: updates better-date-input

- demo/nuxeo-selectivity/index.html
- widgets/nuxeo-selectivity.html
Demos taken from https://arendjr.github.io/selectivity/
> ELEMENTS-554: add demo and fix data in nuxeo-selectivity

- widgets/nuxeo-directory-suggestion.html
- widgets/nuxeo-document-suggestion.html
- widgets/nuxeo-selectivity.html
- widgets/nuxeo-tag-suggestion.html
- widgets/nuxeo-user-suggestion.html
> ELEMENTS-609: add operation and params properties to suggestion widgets

- nuxeo-page-provider-display-behavior.html
- test/nuxeo-data-table-test.html
- widgets/nuxeo-selectivity.html
> improvement-ELEMENTS-673-doNotRefetchRange

- actions/nuxeo-delete-document-button.html
> fix-NXP-25160-noBulkPermanentDelete-9.10

- nuxeo-data-table/default-styles.html
Reverts nuxeo/nuxeo-ui-elements#238
> Revert "ELEMENTS-691: Add <custom-style> tag to data table default styles-9.10"

- nuxeo-page-provider-display-behavior.html
> imp-NXP-25158-noAggs

- widgets/selectivity/selectivity.js
> fix-ELEMENTS-708-selectivityReset

- widgets/selectivity/selectivity.js
> fix-ELEMENTS-708-selectivityReset-9.10

- nuxeo-document-preview.html
> task-ELEMENTS-726-refactor-document-preview

- nuxeo-page-provider-display-behavior.html
> fix-NXP-25302-gridPerf

- widgets/selectivity/selectivity.js
> fix-ELEMENTS-632-resetOnBlur

- widgets/selectivity/selectivity.js
> fix-ELEMENTS-632-resetOnBlur-9.10

- nuxeo-format-behavior.html
> feature-NXP-25512-defaultDateFormat

- nuxeo-format-behavior.html
- widgets/nuxeo-date.html
> fix-ELEMENTS-766-useLocalizedDateFormat

- wct.conf.json
> fix-ELEMENTS-800-saucelabs

- widgets/nuxeo-operation-button.html
Depends on https://github.com/nuxeo/nuxeo-elements/pull/41
> ELEMENTS-806: support async operations

- test/index.html
- test/nuxeo-selectivity.html
- widgets/nuxeo-selectivity.html
> fix-ELEMENTS-818-selectivityClear

- demo/nuxeo-date-picker/index.html
- test/nuxeo-date-picker.html
- widgets/nuxeo-date-picker.html
> feature-ELEMENTS-484-defaultTime

- moment-import.html
- nuxeo-format-behavior.html
> fix-NXP-26277-dynPageLoading

- nuxeo-data-grid/nuxeo-data-grid.html
- widgets/nuxeo-sort-select.html
> fix-ELEMENTS-744-sort-order-910

- widgets/nuxeo-selectivity.html
> ELEMENTS-858: use idFunction and resultFormatter to resolve entries on selectivity(Backport 10.10)

- nuxeo-filter.html
- test/nuxeo-filter.html
https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-ncunha/103/
> fix-ELEMENTS-868-PropertiesNotBeingForwarded

- widgets/nuxeo-document-suggestion.html
https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-ncunha/113/
> ELEMENTS-860: change id function for handling doc refs and selection formatter

- widgets/nuxeo-document-suggestion.html
https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-ncunha/115/
> ELEMENTS-860: change id function for handling doc refs and selection formatter (10.10)

- test/index.html
- test/nuxeo-user-suggestion.html
- widgets/nuxeo-user-suggestion.html
> fix-ELEMENTS-869-prefixedUserGroup

- test/index.html
- test/nuxeo-user-suggestion.html
- widgets/nuxeo-user-suggestion.html
> fix-ELEMENTS-869-prefixedUserGroup-10.10

- widgets/nuxeo-selectivity.html
- widgets/nuxeo-user-group-formatter.html
> fix-ELEMENTS-870-user-group-spacing-10.10

- test/nuxeo-user-suggestion.html
- widgets/nuxeo-user-suggestion.html
> fix-ELEMENTS-912-userDisplayEdit

- package.json
Related to nuxeo/nuxeo-elements#69 and nuxeo/nuxeo-dataviz-elements#14.
> ELEMENTS-926: lock polymer-cli version to 1.6.0

- nuxeo-page-provider-display-behavior.html
Pipeline went through https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/50/
> ELEMENTS-942: remove unnecessary dom flush

- demo/nuxeo-date-picker/index.html
- i18n/messages-pt-PT.json
- widgets/nuxeo-date-picker.html
Pipeline run: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/46/
> ELEMENTS-940: add firstDayOfWeek param for nuxeo-date-picker (Backport 10.10)

- nuxeo-document-preview.html
Related to nuxeo/nuxeo-elements#90.
> ELEMENTS-957: sanitize marked-element (10.10)

- nuxeo-document-preview.html
Related to nuxeo/nuxeo-elements#90 and nuxeo/nuxeo-ui-elements#396.
> ELEMENTS-957: sanitize marked-element (9.10)

- nuxeo-document-preview.html
Related to nuxeo/nuxeo-elements#90, nuxeo/nuxeo-ui-elements#396 and nuxeo/nuxeo-ui-elements#397. Requires nuxeo/nuxeo-web-ui#589.
> ELEMENTS-957: sanitize marked-element (8.10)

- nuxeo-path-suggestion/nuxeo-path-suggestion.html
Pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-9.10/196/
> ELEMENTS-555: improve path suggestion label and styles (Backport 9.10)

- nuxeo-document-preview.html
Pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-9.10/199/
Web UI PR: https://github.com/nuxeo/nuxeo-web-ui/pull/593
> ELEMENTS-591: fix preview of video attachements in Video documents

- test/.eslintrc.json
- test/nuxeo-selectivity.html
- widgets/nuxeo-selectivity.html
Backport of nuxeo/nuxeo-elements#102. Requires nuxeo/nuxeo-elements#103.
> ELEMENTS-911: fix delete with backspace on multi-value selectivity (2.4.x)

- test/nuxeo-selectivity.html
- widgets/nuxeo-selectivity.html
> fix-ELEMENTS-938-idFunction-10.10

- nuxeo-filter.html
> fix-ELEMENTS-737-filter-fwd-props-10.10

- nuxeo-format-behavior.html
- nuxeo-path-suggestion/nuxeo-path-suggestion.html
https://github.com/nuxeo/nuxeo-elements/pull/136
> ELEMENTS-998: escape NXQL string literals (Backport 10.10)

- widgets/nuxeo-file.html
> fix-ELEMENTS-980-fileComplex-10.10

- package.json
Backport of https://github.com/nuxeo/nuxeo-ui-elements/commit/82bc6dab1c754d77e2d56002230de3877d2a0a85 8.10.
> ELEMENTS-935: remove unused npm deps (1.0.x)

- actions/nuxeo-preview-button.html
Pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-9.10/227/
> ELEMENTS-1018: correct preview button stamping (Backport 9.10)

- i18n/messages-ar.json
- i18n/messages-de.json
- i18n/messages-es-ES.json
- i18n/messages-eu.json
- i18n/messages-fr.json
- i18n/messages-he.json
- i18n/messages-id.json
- i18n/messages-it.json
- i18n/messages-ja.json
- i18n/messages-nl.json
- i18n/messages-pt-PT.json
- i18n/messages-sv-SE.json
- i18n/messages-zh-CN.json
- i18n/messages.json
- nuxeo-page-provider-display-behavior.html
Pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/174/
Backporting https://github.com/nuxeo/nuxeo-elements/pull/150
> ELEMENTS-973: internationalized messages on page provider behavior (Backport 10.10)

- nuxeo-user-group-management/nuxeo-create-group.html
- nuxeo-user-group-management/nuxeo-create-user.html
- nuxeo-user-group-management/nuxeo-group-management.html
- nuxeo-user-group-management/nuxeo-user-management.html
> fix-ELEMENTS-1020-RemoveBackButtonUserManagement-9.10

- nuxeo-slots.html
- test/nuxeo-actions-menu.html
- test/nuxeo-slots.html
> fix-ELEMENTS-1012-slot-name-10.10

- nuxeo-filter.html
- nuxeo-filters-behavior.html
- test/nuxeo-filter.html
> feature-ELEMENTS-1046-schemaFilter

- widgets/nuxeo-document-suggestion.html
Backport from https://github.com/nuxeo/nuxeo-elements/pull/161
> ELEMENTS-1054: add missing ecm:path resolution (Backport 10.10)

- nuxeo-filters-behavior.html
- test/nuxeo-filter.html
> feature-NXP-27995-resolveSchemas-10.10

- nuxeo-filters-behavior.html
- test/nuxeo-filter.html
> fix-ELEMENTS-1063-change-schema-name-to-sch-name-10.10

- test/index.html
> fix-ELEMENTS-1093-stab-unit-tests-910

- test/index.html
> fix-ELEMENTS-1093-stab-unit-tests-1010

- actions/nuxeo-preview-button.html
- widgets/nuxeo-dialog.html
> fix-NXP-28138-backportLazyLoadingOnNuxeoDialog

- nuxeo-slots.html
- test/nuxeo-slots.html
Backport of nuxeo/nuxeo-elements#191. Pending 10.10 pipeline check.
> Fix elements 1096 slot dom distribution 10.10

- test/nuxeo-selectivity.html
- widgets/nuxeo-selectivity.html
- widgets/selectivity/selectivity.js
Backport of nuxeo/nuxeo-elements#192. Pending 10.10 pipeline check.
> Fix elements 1090 selectivity reparent 1010

- widgets/nuxeo-user-suggestion.html
> fix-ELEMENTS-1068-GroupNameWithSpecialCharacters-10.10

- actions/nuxeo-add-to-collection-button.html
Related to https://github.com/nuxeo/nuxeo-web-ui/pull/807
Backport from https://github.com/nuxeo/nuxeo-elements/pull/195
> ELEMENTS-1115: ensure collectionId is not reset before firing event (Backport 10.10)

- nuxeo-filter.html
- test/nuxeo-filter.html
Backporting https://jira.nuxeo.com/browse/ELEMENTS-868
Add some random failures on 9.10 pipeline, but none of them seem to have a correlation with this change.
> ELEMENTS-1130: forward properties on nuxeo-filter (Backport 9.10)

- nuxeo-filters-behavior.html
> task-NXP-28644-VersionningAndRetetention-10.10

- nuxeo-layout.html
The PR was not opened automatically due to GitHub down status.
Anyway, the pipeline was 🔵  https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/405/
> ELEMENTS-1172: proceed to native validation first (Backport)

- bower.json
> fix-NXP-29068-update-deps-10.10

- demo/nuxeo-directory-suggestion/index.html
- widgets/selectivity/selectivity.js
Backport of [nuxeo/nuxeo-elements/pull/236](https://github.com/nuxeo/nuxeo-elements/pull/236).
> ELEMENTS-1181: fix selectivity's drop down icon when multivalued (2.4.x)

- widgets/selectivity/selectivity.css
Backport of [nuxeo/nuxeo-elements/pull/248](https://github.com/nuxeo/nuxeo-elements/pull/248).
🔵 [Pipeline status](https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/446/).
> ELEMENTS-1189: set relative positioning on multiple input container (2.4.x)

- test/nuxeo-directory-widgets.html
- widgets/nuxeo-directory-suggestion.html
> fix-ELEMENTS-1202-muti-hierarc-vocab-10.10

- test/nuxeo-directory-widgets.html
- widgets/nuxeo-directory-suggestion.html
Backport of nuxeo/nuxeo-elements#263.
> ELEMENTS-1204: cache directory entries in nuxeo-directory-suggester

- widgets/nuxeo-actions-menu.html
> fix-ELEMENTS-1208-BackportActionsTooltipFix-10.10

- nuxeo-page-provider-display-behavior.html
- test/nuxeo-data-table-test.html
- test/nuxeo-favorites-toggle-button.html
- viewers/nuxeo-video-viewer.html
> fix-NXP-28791-perf-910

- widgets/nuxeo-selectivity.html
…lls when no operation is provided.
> ELEMENTS-1218: fix selectivity when no operation is supplied

- nuxeo-aggregation/nuxeo-dropdown-aggregation.html
- widgets/nuxeo-selectivity.html
- widgets/selectivity/selectivity.css
> fix-ELEMENTS-1230-overflowInNuxeoSelectivity-10.10

- widgets/nuxeo-select.html
Backporting https://github.com/nuxeo/nuxeo-elements/pull/284
> ELEMENTS-1231: expose properties for alignment on nuxeo-select (Backport 10.10)

- nuxeo-format-behavior.html
- test/nuxeo-date-picker.html
- widgets/nuxeo-date-picker.html
- widgets/nuxeo-date.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/289.
> ELEMENTS-1244: add UTC mode to date widgets (10.10)

- nuxeo-user-group-management/nuxeo-group-management.html
> fix-ELEMENTS-1251-deleted-group-10.10

- widgets/nuxeo-selectivity.html
> fix-ELEMENTS-1250-scrollbarsOnNuxeoDirectorySuggestion-10.10

- widgets/nuxeo-date-picker.html
Backport of [nuxeo-elements/pull/307](https://github.com/nuxeo/nuxeo-elements/pull/307).
> ELEMENTS-1223: validate nuxeo-date-picker according to vaadin-date-picker (10.10)

- widgets/nuxeo-selectivity.html
Backport of the https://github.com/nuxeo/nuxeo-elements/pull/312
> ELEMENTS-1275: selectivity dropdown close 10.10

- widgets/nuxeo-operation-button.html
Reverting ELEMENTS-1263 due to https://jira.nuxeo.com/browse/WEBUI-146.
> Revert ELEMENTS-1263

- nuxeo-path-suggestion/nuxeo-path-suggestion.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/329
> ELEMENTS-1299: fix nuxeo-path-suggestion validation (Backport 10.10)

- README.md
- package.json
Backport of [nuxeo-elements/pull/351](https://github.com/nuxeo/nuxeo-elements/pull/351).
> ELEMENTS-1303: update node requirements (2.4.x)

- README.md
- package.json
Backport of [nuxeo-elements/pull/351](https://github.com/nuxeo/nuxeo-elements/pull/351).
> ELEMENTS-1303: update node requirements (2.2.x)

- widgets/nuxeo-operation-button.html
> fix-ELEMENTS-1324-csv-export-10.10

- nuxeo-data-table/data-table-cell.html
- nuxeo-data-table/data-table-checkbox.html
Submitting this PR in name of a customer
> ELEMENTS-1316: enhance style in nuxeo-data-table

- test/nuxeo-date-picker.html
- widgets/nuxeo-date-picker.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/382
> ELEMENTS-1326: use date.get to fix locale usage

- nuxeo-document-preview.html
Backport of [nuxeo-elements/pull/399](https://github.com/nuxeo/nuxeo-elements/pull/399).
> ELEMENTS-1332: fix preview for documents extending note (2.4.x)

- actions/nuxeo-lock-toggle-button.html
- demo/nuxeo-document-suggestion/index.html
- demo/nuxeo-operation-button/index.html
- nuxeo-document-permissions/nuxeo-document-permissions.html
- nuxeo-user-group-management/nuxeo-group-management.html
- nuxeo-user-group-management/nuxeo-user-group-search.html
Elements backport [WEBUI-194](https://jira.nuxeo.com/browse/WEBUI-194) https://github.com/nuxeo/nuxeo-web-ui/pull/1134
> ELEMENTS-1362: remove dots and underscores from http headers

- nuxeo-document-permissions/nuxeo-document-acl-table.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/414
> ELEMENTS-1350: add aclName to Document.RemovePermission request - 10.10

- widgets/nuxeo-file.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/462.
> ELEMENTS-1409: consider uploading property for nuxeo-file validation

- nuxeo-data-table/data-table-settings.html
- nuxeo-data-table/iron-data-table.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/482 for LTS2019.
> ELEMENTS-1430: fix datatable alignment with settings enabled (2.4.x)

- nuxeo-page-provider-display-behavior.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/486
> ELEMENTS-1434: fix display of empty results label when page provider is still updating properties

- widgets/nuxeo-date-picker.html
Backport of [`nuxeo-elements/495`](https://github.com/nuxeo/nuxeo-elements/pull/495).
> ELEMENTS-1450: compute validity based on the current value

- nuxeo-data-table/data-table-cell.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/508.
Cross repo check https://github.com/nuxeo/nuxeo-web-ui/actions/runs/1818624378 🔵
> ELEMENTS-1458: distribute space evenly in data table header cells

- nuxeo-user-group-management/nuxeo-user-management.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/515
It pairs with https://github.com/nuxeo/nuxeo-web-ui/pull/1404.
Cross repo check https://github.com/nuxeo/nuxeo-web-ui/actions/runs/1927868037 🔵
> ELEMENTS-1466: update fetch headers for user management - 2.4.x

- .github/workflows/downstream-check.yaml
- .github/workflows/lint.yaml
- .github/workflows/test.yaml
Pairs with https://github.com/nuxeo/nuxeo-elements/pull/522
Requires https://github.com/nuxeo/nuxeo-ui-elements/pull/559
> ELEMENTS-1473: add nuxeo-elements downstream check

- nuxeo-user-group-management/nuxeo-user-profile.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/527.
> ELEMENTS-1480: fix error handling when changing password in nuxeo-user-profile (10.10)

- nuxeo-page-provider-display-behavior.html
Backport of https://github.com/nuxeo/nuxeo-elements/pull/546.
> ELEMENTS-1495: fix shared copy of filters object (2.4.x)

- nuxeo-document-preview.html
This reverts commit 1845711bcacfdf30bda97683b0a97b958bb055c9.
> Revert "ELEMENTS-1492: add codec to video sources"

- actions/nuxeo-add-to-collection-button.html
https://jira.nuxeo.com/browse/WEBUI-786
The Add button is disabled since no collection is selected
> ELEMENTS-1506: fix return check updated for add to collection button

- nuxeo-user-group-management/nuxeo-user-group-permissions-table.html
https://jira.nuxeo.com/browse/ELEMENTS-1516
6
> ELEMENTS-1516: fix alignment in local permissions of users's profile(BackPort 10.10)

- i18n/messages-ar.json
- i18n/messages-de.json
- i18n/messages-es-ES.json
- i18n/messages-eu.json
- i18n/messages-fr.json
- i18n/messages-he.json
- i18n/messages-id.json
- i18n/messages-it.json
- i18n/messages-ja.json
- i18n/messages-nl.json
- i18n/messages-pt-PT.json
- i18n/messages-sv-SE.json
- i18n/messages-zh-CN.json
- i18n/messages.json
- widgets/nuxeo-uploader-behavior.html
https://jira.nuxeo.com/browse/ELEMENTS-1514
Previously folder upload error was not handled.
> ELEMENTS-1514: handle error Folder upload
